site_name: Opus Guard Documentation Center
site_url: https://docs.opusguard.com
extra_css:
  - stylesheets/extra.css
plugins:
  - search
markdown_extensions:
  - attr_list
  - def_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - header.autohide
  language: en
  logo: /assets/opusguard-logo.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - Products:
      - Content Retention Manager for Confluence: products/content-retention-manager.md
  - Security and Trust:
      - Security Programs: security/security-programs.md
  - Legal:
      - Privacy Policy: legal/privacy.md
      - Terms of Service: legal/tos.md
  - Glossary: glossary.md
